[managers.hyprland]
items = [
  "hyprland",
  "hypridle",
  "hyprland-guiutils",
  "hyprlock",
  "hyprpaper",
  "hyprpicker",
  "hyprland-protocols",
  "hyprland-qt-support",
  #"hyprsunset",
  "xdg-desktop-portal-gtk",
  "xdg-desktop-portal-hyprland",
  "qt5-wayland",
  "walker-launcher",
  "waybar",
  "swaybg",
 ]
