# --------------------- #
#    Generation File    #
# --------------------- #

# Other generation files to import. (Example: intensive_apps -> ~/.config/rebos/imports/intensive_apps.toml)
imports =[
    "drivers",
    "base_packages",
    #"hyprland",
    "plasma",
]

# Packages to be installed via the native package manager.
[managers.system]
items = [
    #"neovim",
    #"hyprland",
]

# Packages to be installed via Flatpak.
[managers.flatpak]
items = [
    # "com.github.tchx84.Flatseal",
]

# Packages to be installed via Cargo.
[managers.cargo]
items = [
    # "bacon",
]
